/**
 * The port agrees with the Python, or it does not ship.
 *
 * `src/dartvision/` is the reference implementation and its 539 tests are the
 * specification. This file does not re-test the logic -- it tests that the
 * JavaScript reproduces what the Python actually computed, on fixtures
 * generated by `tools/make_parity_fixtures.py`.
 *
 * That distinction matters. A hand-written JS test would encode my reading of
 * the Python, and a misreading would pass both. Fixtures encode the Python's
 * behaviour.
 *
 * Run: node --test web/test/
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';

import { nearestBoundary, scoreAt } from '../lib/board.js';
import { apply, estimateHomography } from '../lib/homography.js';
import { assessFraming } from '../lib/framing.js';

const fixtures = JSON.parse(
  readFileSync(fileURLToPath(new URL('../fixtures/parity.json', import.meta.url)), 'utf8'),
);
const BOARD = fixtures.board;

test('scoring matches the Python everywhere a dart can actually land', () => {
  // Python's math.hypot is correctly rounded and no JavaScript expression
  // reproduces it bit-for-bit. Measured across these fixtures, every resulting
  // disagreement sits within a picometre of a boundary radius and none sits
  // anywhere else -- so the assertion is that scoring is exact except on a
  // wire, not that it is exact everywhere.
  const KNIFE_EDGE_MM = 1e-9;
  let worstMargin = 0;
  let onTheWire = 0;

  for (const c of fixtures.scoring) {
    const hit = scoreAt(c.x, c.y, BOARD);
    const boundary = nearestBoundary(c.x, c.y, BOARD);
    worstMargin = Math.max(worstMargin, Math.abs(boundary.distanceMm - c.margin_mm));

    if (c.margin_mm < KNIFE_EDGE_MM) {
      onTheWire += 1;
      continue;
    }
    assert.equal(hit.notation, c.notation, `notation at ${c.x},${c.y}`);
    assert.equal(hit.score, c.score);
    assert.equal(hit.segment, c.segment);
    assert.equal(hit.multiplier, c.multiplier);
    assert.equal(boundary.name, c.boundary, `boundary at ${c.x},${c.y}`);
  }

  assert.ok(worstMargin < 1e-9, `worst margin disagreement ${worstMargin} mm`);
  // The fixtures deliberately place points on every boundary. If that stopped
  // happening the exemption above would quietly stop being tested.
  assert.ok(onTheWire > 20, `only ${onTheWire} fixture points sit on a boundary`);
});

test('the knife-edge exemption only ever catches deliberate boundary points', () => {
  // The exemption is acceptable only if it never swallows a case that stands
  // for a real dart. The first 400 fixtures are sampled uniformly over the
  // board; the rest are placed on boundaries on purpose.
  const sampled = fixtures.scoring.slice(0, 400);
  const exempt = sampled.filter((c) => c.margin_mm < 1e-9);
  assert.equal(exempt.length, 0, 'a randomly placed dart fell inside the exemption');

  // And the band is nine orders of magnitude below anything #21 measures.
  const scored = fixtures.scoring.filter((c) => c.margin_mm >= 1e-9);
  assert.ok(scored.length > 400);
  assert.ok(Math.min(...scored.map((c) => c.margin_mm)) > 1e-3);
});

test('scoring covers the boundaries, not just the easy middle', () => {
  const notations = new Set(fixtures.scoring.map((c) => c.notation));
  for (const expected of ['DB', 'SB', 'MISS', 'T20', 'D20']) {
    assert.ok(notations.has(expected), `fixtures never exercise ${expected}`);
  }
  assert.ok(fixtures.scoring.length > 400);
});

test('the homography matches the Python, including partial landmark sets', () => {
  let worst = 0;
  for (const c of fixtures.homography) {
    const points = c.image_points.map((p) => (p === null ? null : p));
    const h = estimateHomography(points, BOARD);
    c.probes_image.forEach((probe, i) => {
      const [x, y] = apply(h, probe);
      worst = Math.max(worst, Math.hypot(x - c.expected_board[i][0], y - c.expected_board[i][1]));
    });
  }
  // Jacobi eigenvector of AtA versus NumPy's SVD of A: the same vector, found
  // two ways. Sub-micron on a 225 mm board.
  assert.ok(worst < 1e-6, `worst board-coordinate disagreement ${worst} mm`);
});

test('framing verdicts and guidance match the Python exactly', () => {
  let worstElevation = 0;
  let worstRing = 0;

  for (const c of fixtures.framing) {
    const got = assessFraming(c.landmarks, fixtures.image_size);
    const want = c.expected;

    assert.equal(got.verdict, want.verdict,
      `verdict at elevation ${c.true_elevation}: ${got.guidance}`);
    assert.equal(got.guidance.replace(/’/g, "'"), want.guidance.replace(/’/g, "'"));
    assert.equal(got.landmarksFound, want.landmarks_found);

    worstElevation = Math.max(worstElevation, Math.abs(got.elevationDeg - want.elevation_deg));
    worstRing = Math.max(worstRing, Math.abs(got.ringPx - want.ring_px));
  }

  assert.ok(worstElevation < 0.05, `worst elevation disagreement ${worstElevation} deg`);
  assert.ok(worstRing < 0.05, `worst ring-width disagreement ${worstRing} px`);
});

test('the elevation estimate recovers the pose that produced it', () => {
  for (const c of fixtures.framing) {
    const got = assessFraming(c.landmarks, fixtures.image_size);
    assert.ok(Math.abs(got.elevationDeg - c.true_elevation) < 0.5,
      `estimated ${got.elevationDeg} for a true ${c.true_elevation}`);
  }
});

test('every verdict is exercised by the fixtures', () => {
  const verdicts = new Set(fixtures.framing.map((c) => c.expected.verdict));
  for (const expected of ['ready', 'marginal', 'unusable']) {
    assert.ok(verdicts.has(expected), `fixtures never produce ${expected}`);
  }
});
